# Alt text for the Module C figures (house style: every figure has alt text, kept in outputs/figures/alt_text.csv with the Module B, D and E figures).
# Numbers are read from the Module C output tables so the text matches the figures.
source(here::here("R", "theme.R"))
tb <- function(x) readr::read_csv(here::here("outputs", "tables", x), show_col_types = FALSE)
es <- tb("event_study_primary.csv"); att <- tb("overall_att.csv"); sp <- tb("specification_table_raw.csv"); sec <- tb("event_study_secondary_outcomes.csv"); wd <- tb("withdrawal_change_2025Q4_to_2026Q1.csv"); sup <- tb("suppression_share_by_quarter.csv")
e <- function(k) es[es$event_time == k, ]; ov <- att[1, ]
f <- function(path, name, text) { f2 <- file.path(out_dir("figures"), "alt_text.csv"); cur <- if (file.exists(f2)) readr::read_csv(f2, show_col_types = FALSE) else data.frame(figure = character(), alt_text = character())
  cur <- rbind(cur[cur$figure != name, c("figure", "alt_text")], data.frame(figure = name, alt_text = text)); readr::write_csv(cur[order(cur$figure), ], f2) }
f(NULL, "01_coverage_timing_map", "Tile-grid map of the 50 states and DC. Ten states are colored by the year Medicaid coverage of Wegovy and Zepbound began, from 2021 (Kansas) to 2025 (Tennessee); seven states have white tiles with dashed orange outlines because their start quarter is uncertain; the other 34 are gray. Arrows mark five states whose coverage later ended or lapsed.")
f(NULL, "02_adoption_timeline", "Timeline of quarters with Medicaid coverage for the 17 states that ever covered the drugs, 2021 to early 2026, primary states in solid orange and sensitivity states with a light dashed start range followed by solid coverage. Thirteen states are covered in 2026 Q1; California, Pennsylvania, South Carolina and New Hampshire end at the start of 2026 and North Carolina has a gap in late 2025.")
f(NULL, "03_raw_trends_by_cohort", "Nine small-multiple panels, one per adoption cohort of covering states, showing Wegovy and Zepbound prescriptions per 1,000 Medicaid enrollees by quarter against the mean of never-treated states in gray. The rate is zero before 2021, rises after each cohort's start, reaching about 28 per 1,000 for the covering states' mean in 2025 Q3 against about 1 for never-treated states; California and Pennsylvania drop sharply in 2026 Q1 after coverage ended.")
f(NULL, "04_suppression_share", sprintf("Line chart of the maximum share of Wegovy and Zepbound prescriptions that sit in suppressed cells, by quarter from 2021 to 2026. The share is above 10 percent only in the first three quarters (labeled) and is %s percent or less from 2023 Q1 onward.", fmt1(100 * max(sup$max_hidden_share[sup$quarter >= "2023Q1"]))))
f(NULL, "05_withdrawal_descriptive", sprintf("Top: obesity prescriptions per 1,000 enrollees for California, Pennsylvania, South Carolina, North Carolina and New Hampshire around the end of coverage, against continuously covered and never-treated states. Bottom: each state's normalized change from 2025 Q4 to 2026 Q1; California is %s percent and Pennsylvania %s percent, against positive changes in most continuously covered states. Preliminary, descriptive.", fmt1(100 * wd$normalised[wd$unit == "CA"]), fmt1(100 * wd$normalised[wd$unit == "PA"])))
f(NULL, "10_event_study_primary", sprintf("Event-study plot of the estimated effect of coverage on Wegovy and Zepbound prescriptions per 1,000 enrollees by quarter since coverage began. Pre-coverage estimates are near zero; the effect is %s at the start, %s after four quarters and %s after eight, with pointwise 95 percent bands widening later; event times 11 and 12 have fewer than three states and are grayed.", fmt1(e(0)$att), fmt1(e(4)$att), fmt1(e(8)$att)))
f(NULL, "11_specification_chart", sprintf("Forest plot of the overall effect estimate and 95 percent interval for the primary run, %s, and %d sensitivity analyses ranging from %s to %s; all intervals are above zero. The fee-for-service-only specification is not shown because it is not reliably estimable.", fmt1(ov$att), sum(!sp$spec %in% c("0", "12")), fmt1(min(sp$att_simple[!sp$spec %in% c("0", "12")])), fmt1(max(sp$att_simple[!sp$spec %in% c("0", "12")]))))
f(NULL, "12_honestdid", "Line chart of the robust 95 percent confidence interval for the average effect over the first four quarters as the allowed violation of parallel trends (Mbar) rises from 0 to 2. The interval excludes zero until Mbar is about 1.4 (the breakdown value).")
f(NULL, "13_secondary_outcomes", sprintf("Three stacked event-study panels with their own scales: Wegovy and Zepbound (primary), Saxenda and diabetes GLP-1 products. The overall effects are %s, %s and %s prescriptions per 1,000 enrollees; the Saxenda and diabetes intervals include zero.", fmt1(att$att[1]), fmt1(att$att[6]), fmt1(att$att[7])))
cat("alt text rows:", nrow(readr::read_csv(file.path(out_dir("figures"), "alt_text.csv"), show_col_types = FALSE)), "\n")
