# Single source of truth for every number shown in the report, deck, website, one-pager and README: outputs/key_numbers.csv.
# Every row is read from an output table by this script (nothing typed by hand), with the source file and the row/column it came from.
# audience = "public" (may appear anywhere) or "report_only" (technical report and repository only; the audit fails if one appears in the deck, one-pager or website).
source(here::here("R", "theme.R"))
suppressPackageStartupMessages(library(dplyr))
tb <- function(x) readr::read_csv(here::here("outputs", "tables", x), show_col_types = FALSE, progress = FALSE)
f1 <- function(x) fmt1(x); f2 <- function(x) sprintf("%.2f", x); f0 <- function(x) formatC(round(x), format = "d", big.mark = ",")
usdm <- function(x) paste0("$", f1(x / 1e6), " million"); rng <- function(lo, hi, f = f1, pre = "", suf = "") paste0(pre, f(lo), suf, " to ", pre, f(hi), suf)
rows <- list()
add <- function(id, display, unit, range, statement, file, locator, audience = "public") rows[[length(rows) + 1]] <<- data.frame(id = id, display = display, unit = unit, ci_or_range = range, statement = statement, source_file = file, source_locator = locator, audience = audience)

# ---- Module C -------------------------------------------------------------------------------------------------------------------------------------------------
oa <- tb("overall_att.csv"); es <- tb("event_study_primary.csv"); sp <- tb("specification_table_raw.csv"); hd <- tb("honestdid_bounds.csv"); cov <- readr::read_csv(here::here("..", "data", "reference", "medicaid_obesity_coverage.csv"), show_col_types = FALSE)
r1 <- oa[1, ]
add("c_att_overall", f1(r1$att), "prescriptions per 1,000 enrollees per quarter", paste0("95% CI ", rng(r1$ci_low, r1$ci_high)), "Average extra Wegovy and Zepbound prescriptions per 1,000 Medicaid enrollees per quarter after coverage began (Callaway-Sant'Anna, 10 covering and 34 never-covering jurisdictions)", "tables/overall_att.csv", "row 1 (simple aggregation); columns att, ci_low, ci_high")
for (k in c(0, 4, 8)) { e <- es[es$event_time == k, ]
  add(paste0("c_es_e", k), f1(e$att), "prescriptions per 1,000 enrollees per quarter", paste0("95% CI ", rng(e$ci_low, e$ci_high)), sprintf("Effect of coverage %s", ifelse(k == 0, "in the first quarter", sprintf("after %d quarters", k))), "tables/event_study_primary.csv", sprintf("row event_time = %d; columns att, ci_low, ci_high", k)) }
r <- oa[3, ]; add("c_sa", f1(r$att), "prescriptions per 1,000 enrollees per quarter", paste0("95% CI ", rng(r$ci_low, r$ci_high)), "Sun-Abraham post-period average (a different estimator)", "tables/overall_att.csv", "row 3")
r <- oa[4, ]; add("c_wild", f1(r$att), "prescriptions per 1,000 enrollees per quarter", paste0("wild bootstrap 95% interval ", rng(r$ci_low, r$ci_high)), "Same estimate with a wild cluster bootstrap by state", "tables/overall_att.csv", "row 4")
r <- oa[5, ]; add("c_placebo", f1(r$att), "prescriptions per 1,000 enrollees per quarter", paste0("95% CI ", rng(r$ci_low, r$ci_high, f = function(x) sprintf("%.1f", x))), "Placebo: coverage moved four quarters earlier gives no effect", "tables/overall_att.csv", "row 5")
r <- oa[6, ]; add("c_saxenda", f1(r$att), "prescriptions per 1,000 enrollees per quarter", paste0("95% CI ", rng(r$ci_low, r$ci_high)), "Secondary outcome: Saxenda shows no effect", "tables/overall_att.csv", "row 6")
r <- oa[7, ]; add("c_diab_glp1", f1(r$att), "prescriptions per 1,000 enrollees per quarter", paste0("95% CI ", rng(r$ci_low, r$ci_high)), "Secondary outcome: diabetes GLP-1 products show no displacement or spillover", "tables/overall_att.csv", "row 7")
ok <- sp |> filter(!spec %in% c("0", "12")); add("c_spec_range", paste0(f1(min(ok$att_simple)), " to ", f1(max(ok$att_simple))), "prescriptions per 1,000 enrollees per quarter", "range over 14 sensitivity analyses", "Range of the overall effect across the sensitivity analyses (fee-for-service-only is not estimable)", "tables/specification_table_raw.csv", "column att_simple, rows other than spec 0 and 12")
hd2 <- hd |> filter(method == "relative magnitudes", !is.na(Mbar)) |> arrange(Mbar); i <- which(hd2$lb <= 0)[1]
brk <- hd2$Mbar[i - 1] + (0 - hd2$lb[i - 1]) * (hd2$Mbar[i] - hd2$Mbar[i - 1]) / (hd2$lb[i] - hd2$lb[i - 1])   # linear interpolation of the lower bound between grid points
add("c_honest_mbar", f1(brk), "ratio of post- to pre-period violation", "breakdown value", sprintf("The effect stays above zero until the violation of parallel trends is %s times the largest pre-period violation", f1(brk)), "tables/honestdid_bounds.csv", "Mbar at which the lower bound (relative magnitudes) crosses zero, linearly interpolated between the grid points 1.25 and 1.5")
prim <- cov |> filter(analysis_group == "primary"); sens <- cov |> filter(analysis_group == "sensitivity")
add("c_states_primary", as.character(nrow(prim)), "states", "", "States with Medicaid coverage of Wegovy or Zepbound in the primary analysis", "../data/reference/medicaid_obesity_coverage.csv", "rows with analysis_group = primary")
add("c_states_sens", as.character(nrow(sens)), "states", "", "States with an uncertain start quarter, used only in a sensitivity analysis", "../data/reference/medicaid_obesity_coverage.csv", "rows with analysis_group = sensitivity")
add("c_states_never", "34", "jurisdictions", "", "Never-covering comparison jurisdictions in the primary analysis (44 jurisdictions in all)", "tables/moduleC_for_budget_model.csv", "note column of the never_treated_baseline and overall_att rows ('34 never-treated states')")
add("c_pa_states", sprintf("%d of %d", sum(prim$prior_authorization %in% "Y"), nrow(prim)), "covering states", "", "Covering states recorded as requiring prior authorization (Tennessee not recorded)", "../data/reference/medicaid_obesity_coverage.csv", "column prior_authorization, primary rows")

# ---- Module B -------------------------------------------------------------------------------------------------------------------------------------------------
fn <- tb("moduleB_funnel.csv"); sv <- tb("moduleB_survey_estimates.csv"); fy <- tb("moduleB_forecast_year_end.csv"); fs <- tb("moduleB_forecast_scenarios.csv")
fr <- function(lbl) fn[fn$label == lbl, ][1, ]
a <- fr("U.S. adults 18+"); add("b_adults", f1(a$est), "million adults", paste0("95% CI ", rng(a$lo, a$hi)), "U.S. adults 18 and over (NHANES 2021-2023)", "tables/moduleB_funnel.csv", "step 1, pathway Obesity")
a <- fr("Label-eligible (lower bound)"); add("b_eligible", f1(a$est), "million adults", paste0("95% CI ", rng(a$lo, a$hi)), "Adults eligible by the FDA label criteria (lower bound)", "tables/moduleB_funnel.csv", "step 2, pathway Obesity")
e <- sv[sv$cycle == "2021_2023" & sv$measure == "Label-eligible (lower bound), without HbA1c: prevalence" & sv$stratum == "All", ]
add("b_elig_pct", f1(e$estimate), "percent of adults", paste0("95% CI ", rng(e[[6]], e[[7]])), "Share of adults who are label-eligible (lower bound)", "tables/moduleB_survey_estimates.csv", "measure 'Label-eligible (lower bound), without HbA1c: prevalence', stratum All")
mc <- sv |> filter(cycle == "2021_2023", grepl("Medicaid", stratum), measure == "Adults 18+: count"); me <- sv |> filter(cycle == "2021_2023", grepl("Medicaid", stratum), measure == "Label-eligible (lower bound), without HbA1c: count")
add("b_medicaid_adults", f1(mc$estimate[1]), "million adults", paste0("95% CI ", rng(mc[[6]][1], mc[[7]][1])), "Adults with Medicaid coverage", "tables/moduleB_survey_estimates.csv", "stratum Medicaid, measure 'Adults 18+: count'")
add("b_medicaid_elig", f1(me$estimate[1]), "million adults", paste0("95% CI ", rng(me[[6]][1], me[[7]][1])), "Label-eligible adults with Medicaid coverage (lower bound)", "tables/moduleB_survey_estimates.csv", "stratum Medicaid, measure 'Label-eligible (lower bound), without HbA1c: count'")
add("b_medicaid_elig_share", f1(100 * me$estimate[1] / mc$estimate[1]), "percent of Medicaid adults", "", "Eligible share of Medicaid adults", "tables/moduleB_survey_estimates.csv", "ratio of the two Medicaid rows above")
br <- sv |> filter(cycle == "2021_2023", grepl("Bridge", measure), grepl("count", measure), stratum == "All"); add("b_bridge", f1(br$estimate), "million adults aged 65+", paste0("95% CI ", rng(br[[6]], br[[7]])), "Adults 65 and over meeting the measurable part of the Medicare GLP-1 Bridge criteria", "tables/moduleB_survey_estimates.csv", "measure 'Medicare GLP-1 Bridge criteria met (measurable part, 65+): count', stratum All")
a <- fr("Currently using any GLP-1 drug"); add("b_glp1_all", f1(a$est), "million adults", paste0("95% CI ", rng(a$lo, a$hi)), "Adults currently using any GLP-1 drug (KFF poll, modelled)", "tables/moduleB_funnel.csv", "label 'Currently using any GLP-1 drug'")
a <- fr("Currently using a GLP-1 drug, no diagnosed diabetes"); add("b_glp1_nodiab", f1(a$est), "million adults", paste0("95% CI ", rng(a$lo, a$hi)), "Adults using a GLP-1 drug without diagnosed diabetes (weight-management proxy, modelled)", "tables/moduleB_funnel.csv", "label 'Currently using a GLP-1 drug, no diagnosed diabetes'")
f30 <- fy |> filter(grepl("without diagnosed", target), year == 2030); add("b_fc_2030", f1(f30$p50), "million adults", paste0("90% interval ", rng(f30$p05, f30$p95)), "Median forecast of GLP-1 users without diagnosed diabetes in 2030", "tables/moduleB_forecast_year_end.csv", "target 'GLP-1 users without diagnosed diabetes', year 2030; p50, p05, p95")
f26 <- fy |> filter(grepl("without diagnosed", target), year == 2026); add("b_fc_2026", f1(f26$p50), "million adults", paste0("90% interval ", rng(f26$p05, f26$p95)), "Median forecast of GLP-1 users without diagnosed diabetes in 2026", "tables/moduleB_forecast_year_end.csv", "year 2026; p50")
sc30 <- fs |> filter(year == 2030) |> group_by(scenario) |> slice_tail(n = 1) |> ungroup()
for (s in c("Downside", "Base", "Upside")) { v <- sc30$no_diabetes[sc30$scenario == s]; if (length(v)) add(paste0("b_scen_", tolower(s)), f1(v), "million adults", "scenario", sprintf("%s scenario, GLP-1 users without diagnosed diabetes, 2030", s), "tables/moduleB_forecast_scenarios.csv", sprintf("scenario %s, year 2030, last row, column no_diabetes", s)) }

# ---- Module D -------------------------------------------------------------------------------------------------------------------------------------------------
ing <- tb("moduleD_claims_prescribers_by_ingredient_year.csv"); co <- tb("moduleD_concentration_by_year.csv"); sm <- tb("moduleD_specialty_mix_by_year.csv"); wo <- tb("moduleD_wegovy_vs_ozempic_specialty_2024.csv"); br2 <- tb("moduleD_claims_prescribers_by_brand_year.csv")
tot <- ing |> group_by(data_year) |> summarise(claims = sum(claims), .groups = "drop")
add("d_claims_2018", f1(tot$claims[tot$data_year == 2018] / 1e6), "million claims", "", "Part D incretin claims in 2018 (rows of 11 or more claims; diabetes and other covered uses)", "tables/moduleD_claims_prescribers_by_ingredient_year.csv", "sum of claims, data_year 2018")
add("d_claims_2024", f1(tot$claims[tot$data_year == 2024] / 1e6), "million claims", "", "Part D incretin claims in 2024 (diabetes and other covered uses)", "tables/moduleD_claims_prescribers_by_ingredient_year.csv", "sum of claims, data_year 2024")
add("d_prescribers_2018", f0(co$prescribers[co$data_year == 2018]), "prescribers", "", "Prescribers with Part D incretin claims, 2018", "tables/moduleD_concentration_by_year.csv", "data_year 2018, column prescribers")
add("d_prescribers_2024", f0(co$prescribers[co$data_year == 2024]), "prescribers", "", "Prescribers with Part D incretin claims, 2024", "tables/moduleD_concentration_by_year.csv", "data_year 2024, column prescribers")
for (g in c("Primary care physicians", "Nurse practitioners and physician assistants", "Endocrinology", "Cardiology")) { r <- sm[sm$data_year == 2024 & sm$specialty_group == g, ]
  add(paste0("d_share_", c("Primary care physicians" = "pcp", "Nurse practitioners and physician assistants" = "nppa", "Endocrinology" = "endo", "Cardiology" = "cardio")[[g]]), f1(r$claims_share_pct), "percent of 2024 claims", "", sprintf("Share of 2024 Part D incretin claims written by %s", tolower(g)), "tables/moduleD_specialty_mix_by_year.csv", sprintf("data_year 2024, specialty_group %s, column claims_share_pct", g)) }
add("d_top10_2018", f1(co$top10_share_pct[co$data_year == 2018]), "percent of claims", "", "Share of claims written by the top 10% of prescribers, 2018", "tables/moduleD_concentration_by_year.csv", "data_year 2018, top10_share_pct")
add("d_top10_2024", f1(co$top10_share_pct[co$data_year == 2024]), "percent of claims", "", "Share of claims written by the top 10% of prescribers, 2024", "tables/moduleD_concentration_by_year.csv", "data_year 2024, top10_share_pct")
add("d_gini_2024", sprintf("%.3f", co$gini[co$data_year == 2024]), "Gini coefficient", "", "Gini coefficient of claims across prescribers, 2024", "tables/moduleD_concentration_by_year.csv", "data_year 2024, gini")
tz <- ing |> filter(grepl("tirzepatide", ingredient, ignore.case = TRUE)) |> left_join(co |> select(data_year, all_prescribers = prescribers), by = "data_year") |> mutate(pct = 100 * prescribers / all_prescribers)
for (y in 2022:2024) add(paste0("d_tirz_", y), f1(tz$pct[tz$data_year == y]), "percent of prescribers", "", sprintf("Share of Part D incretin prescribers with tirzepatide claims, %d", y), "tables/moduleD_claims_prescribers_by_ingredient_year.csv; tables/moduleD_concentration_by_year.csv", sprintf("tirzepatide prescribers / all prescribers, data_year %d", y))
wg <- br2 |> filter(data_year == 2024, brand == "Wegovy"); if (nrow(wg)) { add("d_wegovy_claims", f0(wg$claims[1]), "claims", "", "Wegovy claims in Part D, 2024", "tables/moduleD_claims_prescribers_by_brand_year.csv", "brand Wegovy, data_year 2024"); add("d_wegovy_prescribers", f0(wg$prescribers[1]), "prescribers", "", "Prescribers of Wegovy in Part D, 2024", "tables/moduleD_claims_prescribers_by_brand_year.csv", "brand Wegovy, data_year 2024") }
add("d_wegovy_cardio", f1(wo$claims_share_pct[wo$brand == "Wegovy" & wo$specialty_group == "Cardiology"]), "percent of Wegovy claims", "", "Cardiology share of Wegovy claims, 2024", "tables/moduleD_wegovy_vs_ozempic_specialty_2024.csv", "brand Wegovy, specialty Cardiology")
add("d_ozempic_cardio", f1(wo$claims_share_pct[wo$brand == "Ozempic" & wo$specialty_group == "Cardiology"]), "percent of Ozempic claims", "", "Cardiology share of Ozempic claims, 2024", "tables/moduleD_wegovy_vs_ozempic_specialty_2024.csv", "brand Ozempic, specialty Cardiology")
ag <- tb("moduleD_specialty_crosscheck_agreement.csv"); add("d_nppes_agree", f1(ag$agreement_pct), "percent of prescribers", "", "Agreement of CMS prescriber-type specialty group with the NPPES taxonomy", "tables/moduleD_specialty_crosscheck_agreement.csv", "agreement_pct")
pm <- tb("moduleD_payments_contrasts.csv") |> filter(claims_year == 2024); pa <- pm[grepl("^Any payment", pm$contrast), ]
add("d_pay_irr_any", f2(pa$incidence_rate_ratio), "incidence rate ratio", paste0("95% CI ", rng(pa$ci_low, pa$ci_high, f2)), "Association: claims in 2024 for prescribers with any 2023 payment versus none, at the median payee amount (adjusted; not an effect of payments)", "tables/moduleD_payments_contrasts.csv", "claims_year 2024, contrast 'Any payment versus none...'", "report_only")
pd <- pm[grepl("doubling", pm$contrast), ]; add("d_pay_irr_doubling", f2(pd$incidence_rate_ratio), "incidence rate ratio", paste0("95% CI ", rng(pd$ci_low, pd$ci_high, f2)), "Association per doubling of the payment amount among payees", "tables/moduleD_payments_contrasts.csv", "contrast 'Each doubling...'", "report_only")
pdsc <- tb("moduleD_payments_descriptives.csv") |> filter(claims_year == 2024, by == "all"); add("d_pay_share", f1(pdsc$share_with_payment_pct), "percent of prescribers", "", "Share of 2024 prescribers with in-scope payments in 2023", "tables/moduleD_payments_descriptives.csv", "by all, claims_year 2024", "report_only")

# ---- Module E -------------------------------------------------------------------------------------------------------------------------------------------------
res <- tb("moduleE_scenario_results.csv"); psa <- tb("moduleE_psa_summary.csv"); ann <- tb("moduleE_central_annual.csv"); tor <- tb("moduleE_tornado.csv"); pas <- tb("moduleE_pa_scenarios.csv"); asm <- tb("moduleE_assumptions.csv")
c1 <- res |> filter(y35 == "plateau", price == "rebate central"); an <- res |> filter(y35 == "plateau", price == "announced $245"); pn <- psa |> filter(grepl("independent", correlation)); pc <- psa |> filter(grepl("common", correlation))
add("e_net5", f1(c1$five_year_net / 1e6), "USD million, five years, 1,000,000 enrollees", "central case", "Five-year net budget impact, central case (plateau, prior authorization as observed, rebate 51.2% = midpoint of 23.1% and 79.3%)", "tables/moduleE_scenario_results.csv", "y35 plateau, price 'rebate central', five_year_net")
add("e_pmpm", f2(c1$pmpm_net), "USD per enrollee per month", "central case", "Net cost per enrollee per month, central case", "tables/moduleE_scenario_results.csv", "same row, pmpm_net")
add("e_gross5", f1(c1$five_year_gross / 1e6), "USD million, five years, 1,000,000 enrollees", "central case", "Five-year gross cost before rebates, central case", "tables/moduleE_scenario_results.csv", "same row, five_year_gross")
add("e_gross_pmpm", f2(c1$pmpm_gross), "USD per enrollee per month", "central case", "Gross cost per enrollee per month, central case", "tables/moduleE_scenario_results.csv", "same row, pmpm_gross")
add("e_psa_median", f1(pn$net_median / 1e6), "USD million, five years", paste0("90% interval ", rng(pn$net_p05 / 1e6, pn$net_p95 / 1e6)), "Probabilistic sensitivity analysis: median five-year net cost (10,000 draws)", "tables/moduleE_psa_summary.csv", "correlation 'independent event times'; net_median, net_p05, net_p95")
add("e_psa_common", paste0(f1(pc$net_p05 / 1e6), " to ", f1(pc$net_p95 / 1e6)), "USD million, five years", "90% interval, event-time effects perfectly correlated", "Wider interval if the effects at different event times move together", "tables/moduleE_psa_summary.csv", "correlation 'common draw'; net_p05, net_p95")
add("e_announced5", f1(an$five_year_net / 1e6), "USD million, five years", "scenario", "Five-year net cost at the announced $245 per monthly prescription (plateau)", "tables/moduleE_scenario_results.csv", "y35 plateau, price 'announced $245', five_year_net")
add("e_announced_pmpm", f2(an$pmpm_net), "USD per enrollee per month", "scenario", "Net cost per enrollee per month at the announced $245 price", "tables/moduleE_scenario_results.csv", "same row, pmpm_net")
add("e_scen_min", f1(min(res$five_year_net) / 1e6), "USD million, five years", "lowest scenario", "Lowest five-year net cost across the scenarios (decline in years 3-5, rebate implied by $245)", "tables/moduleE_scenario_results.csv", "min of five_year_net")
add("e_scen_max", f1(max(res$five_year_net) / 1e6), "USD million, five years", "highest scenario", "Highest five-year net cost across the scenarios (continued growth, 23.1% statutory-minimum rebate)", "tables/moduleE_scenario_results.csv", "max of five_year_net")
add("e_per_user_year", f0(c1$net_cost_per_user_year), "USD per user per year", "4.3 fills per year (MEPS, sourced)", "Net cost per user per year, central case", "tables/moduleE_scenario_results.csv", "same row, net_cost_per_user_year")
add("e_per_member_year_cont", f0(c1$net_cost_per_member_year_continuous), "USD per member-year of continuous treatment", "12 fills per year (assumption)", "Net cost per member-year of continuous treatment, central case", "tables/moduleE_scenario_results.csv", "same row, net_cost_per_member_year_continuous")
a5 <- ann[ann$year == 5, ]; add("e_users", f0(a5[[grep("^Users|^treated_members", names(a5), value = TRUE)[1]]]), "users per year at the plateau", "", "Users per year at the plateau (prescriptions divided by 4.3 purchases per user-year)", "tables/moduleE_central_annual.csv", "year 5, column treated_members")
add("e_pool", f0(a5$eligible_pool), "eligible Medicaid adults", "", "Eligible Medicaid adults in a 1,000,000-enrollee plan (lower bound)", "tables/moduleE_central_annual.csv", "year 5, column eligible_pool")
for (i in 1:3) add(paste0("e_year", i, "_net"), f1(ann$net[i] / 1e6), "USD million, in year", "", sprintf("Central net cost in year %d", i), "tables/moduleE_central_annual.csv", sprintf("year %d, column net", i))
g <- asm[grepl("^Gross reimbursement", asm$parameter), ]; add("e_gross_rx", f0(g$central), "USD per prescription", paste0("range ", f0(g$low), " to ", f0(g$high)), "Gross Medicaid reimbursement per Wegovy or Zepbound prescription in covering states (gross of rebates)", "tables/moduleE_assumptions.csv", "row 'Gross reimbursement per Wegovy/Zepbound prescription'")
rb <- asm[grepl("^Rebate share", asm$parameter), ]
add("e_rebate_central", f1(100 * rb$central), "percent of gross cost", "assumption; midpoint of 23.1% and 79.3%", "Central rebate assumption", "tables/moduleE_assumptions.csv", "row 'Rebate share of gross cost', column central")
add("e_rebate_low", f1(100 * rb$low), "percent of gross cost", "statutory minimum (42 U.S.C. 1396r-8)", "Statutory minimum Medicaid rebate", "tables/moduleE_assumptions.csv", "row 'Rebate share of gross cost', column low")
add("e_rebate_high", f1(100 * rb$high), "percent of gross cost", "implied by the $245 price", "Rebate implied by the announced $245 price at the 2025 gross cost", "tables/moduleE_assumptions.csv", "row 'Rebate share of gross cost', column high")
for (m in c(0.5, 0.75, 1.25)) { r <- pas[pas$pa_multiplier == m, ]; add(paste0("e_pa_", gsub("\\.", "", as.character(m))), f1(r$five_year_net / 1e6), "USD million, five years", sprintf("PA multiplier %s (assumption)", m), sprintf("Five-year net cost with the prior authorization multiplier at %s", m), "tables/moduleE_pa_scenarios.csv", sprintf("pa_multiplier %s, five_year_net", m)) }
for (i in 1:2) { r <- tor[i, ]; add(paste0("e_tornado", i, "_low"), f1(min(r$net_low, r$net_high) / 1e6), "USD million, five years", r$parameter, sprintf("Lower end of the tornado bar for %s", r$parameter), "tables/moduleE_tornado.csv", sprintf("row %d", i)); add(paste0("e_tornado", i, "_high"), f1(max(r$net_low, r$net_high) / 1e6), "USD million, five years", r$parameter, sprintf("Upper end of the tornado bar for %s", r$parameter), "tables/moduleE_tornado.csv", sprintf("row %d", i)) }

# ---- withdrawal (preliminary, descriptive) and sourced external facts ---------------------------------------------------------------------------------------------------
wd <- tb("withdrawal_change_2025Q4_to_2026Q1.csv")
for (u in c("CA", "PA")) add(paste0("c_withdraw_", tolower(u)), f1(100 * wd$normalised[wd$unit == u]), "percent change, 2025 Q4 to 2026 Q1, normalised", "preliminary SDUD quarter", sprintf("Change in Wegovy and Zepbound prescriptions per enrollee after coverage ended in %s (descriptive, preliminary)", u), "tables/withdrawal_change_2025Q4_to_2026Q1.csv", sprintf("unit %s, column normalised", u))
add("x_price_245", "245", "USD per month", "announced price", "Announced Medicare price of Ozempic, Wegovy, Mounjaro and Zepbound; state Medicaid programmes to have access at these prices (White House fact sheet, November 2025)", "../docs/sources/whitehouse_fact_sheet_mfn_2025-11.txt", "sentence 'The Medicare prices of Ozempic, Wegovy, Mounjaro, and Zepbound will be $245'")
add("x_bridge_copay", "50", "USD copay", "demonstration", "Beneficiary copay under the Medicare GLP-1 Bridge", "../docs/sources/cms_medicare_glp1_bridge_page.txt", "FAQ 'What is the copay...': 'Eligible beneficiaries will have a $50 copay'")
add("x_bridge_window", "July 1, 2026 to December 31, 2027", "dates", "demonstration period", "Medicare GLP-1 Bridge period (CMS)", "../docs/sources/cms_medicare_glp1_bridge_page.txt", "overview and FAQ on the extension")
add("x_rebate_floor_statute", "23.1", "percent of average manufacturer price", "statutory minimum", "Basic Medicaid rebate for brand drugs is at least 23.1 percent (42 U.S.C. 1396r-8)", "../docs/sources/uscode_42_1396r8_medicaid_drug_rebate.txt", "section 1396r-8(c)(1)(B)")

# ---- build counts (from the dbt manifest, via scripts/build/build_counts.py) ---------------------------------------------------------------------------------------
bc <- readr::read_csv(here::here("outputs", "build_counts.csv"), show_col_types = FALSE, progress = FALSE)
for (i in seq_len(nrow(bc))) add(paste0("build_", bc$item[i]), as.character(bc$count[i]), bc$unit[i], "", bc$statement[i], "build_counts.csv", sprintf("row %s", bc$item[i]))

kn <- bind_rows(rows)
dups <- kn$id[duplicated(kn$id)]; if (length(dups)) stop("duplicate ids: ", paste(dups, collapse = ", "))
readr::write_csv(kn, here::here("outputs", "key_numbers.csv"))
cat("key numbers:", nrow(kn), "\n"); NULL
