# Data for the app: small aggregate CSVs in app/data (generated by analysis/scripts/46_app_data.R and 41_moduleE_model.R, checked against key_numbers.csv by analysis/scripts/45_check_app_data.R).
# Nothing here is row-level: state-quarter values are observed (unsuppressed) prescriptions per 1,000 Medicaid enrollees; counts under 11 are never shown.
read_app_csv <- function(f) utils::read.csv(file.path("data", f), stringsAsFactors = FALSE, na.strings = c("", "NA"))
EFF <- read_app_csv("moduleC_effects.csv"); SET <- read_app_csv("model_settings.csv")
.g <- function(param, col) SET[[col]][SET$parameter == param]
INP <- list(att = data.frame(e = EFF$event_quarter, estimate = EFF$estimate, se = EFF$se, ci_low = EFF$ci_low, ci_high = EFF$ci_high),
            gross = list(central = .g("gross_cost_per_prescription", "central"), low = .g("gross_cost_per_prescription", "low"), high = .g("gross_cost_per_prescription", "high")),
            rebate = list(central = .g("rebate_share", "central"), low = .g("rebate_share", "low"), high = .g("rebate_share", "high")), announced = .g("announced_net_price", "central"),
            fills = list(central = .g("purchases_per_user_year", "central"), low = .g("purchases_per_user_year", "low"), high = .g("purchases_per_user_year", "high")),
            adult_share = .g("adult_share_of_enrollment", "central"), eligible_share = .g("eligible_share_of_medicaid_adults", "central"))
BASE <- bia_defaults(INP)
KF <- read_app_csv("key_facts.csv")
kf <- function(id, what = "display") { v <- KF[[what]][KF$id == id]; if (length(v) != 1) stop("key fact not found: ", id); v }
kf_ci <- function(id) sub("^(95%|90%) (CI|interval) ", "", kf(id, "ci_or_range"))
ES <- read_app_csv("event_study.csv"); SPECS <- read_app_csv("specifications.csv"); OVERALL <- read_app_csv("overall_effects.csv")
STATES <- read_app_csv("states.csv"); RATES <- read_app_csv("state_quarter_rates.csv"); NEVER <- read_app_csv("never_covered_mean.csv")
ENROLL <- read_app_csv("state_enrollment.csv"); ASSUMP <- read_app_csv("assumptions.csv")
RATES$coverage_active <- as.logical(RATES$coverage_active); ES$fewer_than_3_states <- as.logical(ES$fewer_than_3_states); SPECS$estimable <- as.logical(SPECS$estimable)
QLAB <- sort(unique(RATES$quarter_label))
