-- generated by scripts/build/gen_dbt_wide_models.py
select
    '2021_2023' as cycle,
    "SEQN" as seqn,
    "BPAOARM" as bpaoarm,
    "BPAOCSZ" as bpaocsz,
    "BPXOSY1" as bpxosy1,
    "BPXODI1" as bpxodi1,
    "BPXOSY2" as bpxosy2,
    "BPXODI2" as bpxodi2,
    "BPXOSY3" as bpxosy3,
    "BPXODI3" as bpxodi3,
    "BPXOPLS1" as bpxopls1,
    "BPXOPLS2" as bpxopls2,
    "BPXOPLS3" as bpxopls3
from {{ source('raw', 'nhanes_bpxo_l') }}
union all
select
    '2017_2020' as cycle,
    "SEQN" as seqn,
    "BPAOARM" as bpaoarm,
    "BPAOCSZ" as bpaocsz,
    "BPXOSY1" as bpxosy1,
    "BPXODI1" as bpxodi1,
    "BPXOSY2" as bpxosy2,
    "BPXODI2" as bpxodi2,
    "BPXOSY3" as bpxosy3,
    "BPXODI3" as bpxodi3,
    "BPXOPLS1" as bpxopls1,
    "BPXOPLS2" as bpxopls2,
    "BPXOPLS3" as bpxopls3
from {{ source('raw', 'nhanes_p_bpxo') }}
