-- generated by scripts/build/gen_dbt_wide_models.py
select
    '2021_2023' as cycle,
    "SEQN" as seqn,
    "BPQ020" as bpq020,
    "BPQ030" as bpq030,
    "BPQ150" as bpq150,
    "BPQ080" as bpq080,
    "BPQ101D" as bpq101d,
    null::double precision as bpd035,
    null::double precision as bpq040a,
    null::double precision as bpq050a,
    null::double precision as bpq060,
    null::double precision as bpq070,
    null::double precision as bpq090d,
    null::double precision as bpq100d
from {{ source('raw', 'nhanes_bpq_l') }}
union all
select
    '2017_2020' as cycle,
    "SEQN" as seqn,
    "BPQ020" as bpq020,
    "BPQ030" as bpq030,
    null::double precision as bpq150,
    "BPQ080" as bpq080,
    null::double precision as bpq101d,
    "BPD035" as bpd035,
    "BPQ040A" as bpq040a,
    "BPQ050A" as bpq050a,
    "BPQ060" as bpq060,
    "BPQ070" as bpq070,
    "BPQ090D" as bpq090d,
    "BPQ100D" as bpq100d
from {{ source('raw', 'nhanes_p_bpq') }}
