-- generated by scripts/build/gen_dbt_wide_models.py
select
    '2021_2023' as cycle,
    "SEQN" as seqn,
    "HIQ011" as hiq011,
    "HIQ032A" as hiq032a,
    "HIQ032B" as hiq032b,
    "HIQ032C" as hiq032c,
    "HIQ032D" as hiq032d,
    "HIQ032E" as hiq032e,
    "HIQ032F" as hiq032f,
    "HIQ032H" as hiq032h,
    "HIQ032I" as hiq032i,
    "HIQ210" as hiq210,
    null::double precision as hiq032j,
    null::double precision as hiq260,
    null::double precision as hiq105,
    null::double precision as hiq270
from {{ source('raw', 'nhanes_hiq_l') }}
union all
select
    '2017_2020' as cycle,
    "SEQN" as seqn,
    "HIQ011" as hiq011,
    "HIQ032A" as hiq032a,
    "HIQ032B" as hiq032b,
    "HIQ032C" as hiq032c,
    "HIQ032D" as hiq032d,
    "HIQ032E" as hiq032e,
    null::double precision as hiq032f,
    "HIQ032H" as hiq032h,
    "HIQ032I" as hiq032i,
    "HIQ210" as hiq210,
    "HIQ032J" as hiq032j,
    "HIQ260" as hiq260,
    "HIQ105" as hiq105,
    "HIQ270" as hiq270
from {{ source('raw', 'nhanes_p_hiq') }}
