-- generated by scripts/build/gen_dbt_wide_models.py
select
    '2021_2023' as cycle,
    "SEQN" as seqn,
    "RXQ033" as rxq033,
    "RXQ050" as rxq050,
    null::double precision as rxduse,
    null::text as rxddrug,
    null::text as rxddrgid,
    null::double precision as rxqseen,
    null::double precision as rxddays,
    null::text as rxdrsc1,
    null::text as rxdrsc2,
    null::text as rxdrsc3,
    null::text as rxdrsd1,
    null::text as rxdrsd2,
    null::text as rxdrsd3,
    null::double precision as rxdcount
from {{ source('raw', 'nhanes_rxq_rx_l') }}
union all
select
    '2017_2020' as cycle,
    "SEQN" as seqn,
    null::double precision as rxq033,
    null::double precision as rxq050,
    "RXDUSE" as rxduse,
    "RXDDRUG" as rxddrug,
    "RXDDRGID" as rxddrgid,
    "RXQSEEN" as rxqseen,
    "RXDDAYS" as rxddays,
    "RXDRSC1" as rxdrsc1,
    "RXDRSC2" as rxdrsc2,
    "RXDRSC3" as rxdrsc3,
    "RXDRSD1" as rxdrsd1,
    "RXDRSD2" as rxdrsd2,
    "RXDRSD3" as rxdrsd3,
    "RXDCOUNT" as rxdcount
from {{ source('raw', 'nhanes_p_rxq_rx') }}
