-- generated by scripts/build/gen_dbt_wide_models.py
select
    '2021_2023' as cycle,
    "SEQN" as seqn,
    "WTPH2YR" as wtph2yr,
    "LBXGH" as lbxgh
from {{ source('raw', 'nhanes_ghb_l') }}
union all
select
    '2017_2020' as cycle,
    "SEQN" as seqn,
    null::double precision as wtph2yr,
    "LBXGH" as lbxgh
from {{ source('raw', 'nhanes_p_ghb') }}
